name: Build and Release

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: gateway
  REGISTRY: ghcr.io
  CHART_NAME: gateway
  CHART_REPO_OWNER: Abstractize
  CHART_REPO_NAME: todo.charts

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase env vars for username and repo
        id: set_env
        run: |
          USERNAME=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d/ -f2)
          REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REPO_NAME_LOWER=$REPO_NAME_LOWER" >> $GITHUB_ENV
          echo "USERNAME=$USERNAME" >> $GITHUB_OUTPUT
          echo "REPO_NAME_LOWER=$REPO_NAME_LOWER" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            GITHUB_USERNAME=${{ github.repository_owner }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.set_env.outputs.USERNAME }}/${{ steps.set_env.outputs.REPO_NAME_LOWER }}:latest
            ${{ env.REGISTRY }}/${{ steps.set_env.outputs.USERNAME }}/${{ steps.set_env.outputs.REPO_NAME_LOWER }}:${{ github.sha }}

  helm-release:
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Update Chart.yaml version and appVersion
        run: |
          sudo apt-get update && sudo apt-get install -y yq
          VERSION="0.1.${GITHUB_RUN_NUMBER}"
            yq -y -i ".appVersion = \"${GITHUB_SHA}\" | .version = \"$VERSION\"" .helm/Chart.yaml

      - name: Lint Helm chart
        run: helm lint .helm

      - name: Package Helm chart
        run: helm package .helm --destination charts

      - name: Chart Releaser - Setup
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.5.0

      - name: Chart Releaser - Release
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts