name: PR Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm lint
        run: helm lint .helm

  docker-build-test:
    runs-on: ubuntu-latest
    needs: helm-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create secret file
        run: echo "${{ secrets.GITHUB_TOKEN }}" > /tmp/github_token.txt

      - name: Build Docker image with secret
        run: |
          docker buildx build \
            --build-arg GITHUB_USERNAME=${{ github.actor }} \
            --secret id=GITHUB_TOKEN,src=/tmp/github_token.txt \
            --tag test-image:pr-${{ github.event.pull_request.number }} \
            --load \
            -f Dockerfile \
            .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run container test
        run: docker run --rm test-image:pr-${{ github.event.pull_request.number }} sleep 5